### ISSUE TITLE
파라미터 로드 실패 문의

### ISSUE THREAD

**Issue by hsol** [ridi/ePub-Validator#4]
https://github.com/ridibooks/ePub-Validator/blob/0de29a0dc18abebd3a81d378446653cc3c089ea8/epub-validator.js#L64

클론받아서 테스트 중에 하도 zip 파일이 아니라는 메시지를 띄워서 열어보니 file 에 들어가는 파라미터가 첫번째 파라미터네요.

이러면 ```node epub-validator.js ${file-path}``` 했을 때 ```epub-validator.js``` 를 가져올텐데, 혹시 사용 방법이 틀린건가요?

**Comment by DavinAhn** [comment]
@hsol 
아, 이것은 NodeJS 버전 때문입니다 ㅠ
최신 버전에 맞춘 대응이 필요해 보이네요.
우선, project root directory에서 `make release` 후 `./release/epub-validator ${file-path}`를 이용해주세요.

**Comment by DavinAhn** [comment]
@hsol 
0.0.3에서 수정했습니다.
